### ISSUE TITLE
Not working in webpack

### ISSUE THREAD

**Issue by gre** [foliojs/linebreak#1]
```
ERROR in ./~/{my lib}/~/linebreak/src/linebreaker.js
Module not found: Error: Cannot resolve module 'fs' in {my lib}/node_modules/linebreak/src
 @ ./~/{my lib}/~/linebreak/src/linebreaker.js 7:7-20
```

**Comment by gre** [comment]
a solution would be to publish on NPM a static version of the library (not the version that needs brfs)

**Comment by gre** [comment]
^ i've attempted to do this in this commit. I basically works but the problem is that it's still a (bare) bundle.. Do you know if there is a way to just preprocess the brfs to get rid of the transform dependency?

**Comment by devongovett** [comment]
Try something like https://github.com/MarkReeder/webpack-browserify-transform-loaders-plugin, which will load browserify transforms in webpack. The npm version is currently not working (hopefully fixed soon), but try my fork https://github.com/devongovett/webpack-browserify-transform-loaders-plugin/tree/patch-2.

**Comment by devongovett** [comment]
Alternatively, just load brfs yourself in your webpack config https://github.com/Flipboard/react-canvas/blob/master/webpack.config.js#L22

**Comment by gre** [comment]
Interoperability across libs is tough at the moment, there are tons of different techs published on NPM. I don't know if there is a single answer to this, but I like the idea that all published libs are "precompiled" down to ES5 (and no plugin or transform required).

Anyway, i'll stick with the idea that linebreak is published with a dep on brfs and i'll try that plugin. (BTW I couldn't make the brfs transform working with other loaders (babel, etc..), but that's probably my mistake).

**Comment by devongovett** [comment]
I don't like precompiling because it doesn't work with source maps in browserify as far as I know. If you let browserify/webpack compile modules when your app is being built, you get better source map support. I've also gotten webpack warnings before about using prebuilt modules - they specifically warn against it.

**Comment by gre** [comment]
agreed on this. It's tricky.

**Comment by mattdesl** [comment]
Some discussion/solutions on this here:
https://gist.github.com/mattdesl/aaf759da84cc44c22305

**Comment by gre** [comment]
@mattdesl cool :)
cheers

**Comment by mattdesl** [comment]
I think the easiest is to use `ify-loader` for webpack so that all modules work as the (browserify) author intended. But it still won't work in all bundlers (jspm etc) and requires additional set up for the end-user.

**Comment by devongovett** [comment]
@mattdesl thanks. ify-loader looks better than the one I linked above.

**Comment by gre** [comment]
ify works great :+1:

**Comment by cinan** [comment]
(I know this issue is too old, but Readme lacks this kind of information)

`ify-loader` isn't working for me, I found `transform-loader` does the same job:

```
{
  test: /node_modules\/linebreak/,
  loader: 'transform-loader?brfs',
  enforce: 'post'
}
```
