### ISSUE TITLE
`npm audit` flags `brfs` as a security vulnerability

### ISSUE THREAD

**Issue by mclark-newvistas** [foliojs/linebreak#12]
Would it be possible to move `brfs` to `devDependencies`? PDFKit has it in the `devDependencies`, which would fix the `npm audit` warnings about security vulnerabilities for both these libraries. See also bpampuch/pdfmake#1639.

**Comment by ghost** [comment]
This is broken for end-users, both as bare *linebreak* package and downstream for *pdfkit*

Moderate:         Sandbox Breakout / Arbitrary Code Execution
Package:           static-eval
Patched in:        No patch available
Dependency of: linebreak
Path:                  linebreak > brfs > static-module > static-eval
More info:          https://npmjs.com/advisories/758

**Comment by liborm85** [comment]
brfs updated in version 1.0.0
