### ISSUE TITLE
Missing LICENSE file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [foliojs/linebreak#15]
I found 2 license-related problems:

- [ ] missing `LICENSE` file at top of repo
   + it should contain your copyright info
   + you've indicated MIT: https://opensource.org/licenses/MIT
- [ ] missing `LICENSE` file in the release tarball (under https://registry.npmjs.org/)

**Comment by devongovett** [comment]
Fixed by c7873ab973ca11576c50e49803b1fecbe531ed96.
