### ISSUE TITLE
Redundant 'if' statement

### ISSUE THREAD

**Issue by toptensoftware** [foliojs/linebreak#26]
I was porting this to C# and getting "not all control paths return a value" errors.  Pretty sure this 'if' statement is redundant due to the preceding "while" statement's condition.

https://github.com/foliojs/linebreak/blob/9096a22b389ea62df45252638d7bd6ebaab0f72d/src/linebreaker.js#L191

Thanks for your work on this :)

**Comment by liborm85** [comment]
Thanks. Fixed by commit https://github.com/foliojs/linebreak/commit/05f28997b4f9f12a665580c99272cf845aa822d8.
