### ISSUE TITLE
Not able to integrate this library for ReactJS. Guidelines / Fix needed.

### ISSUE THREAD

**Issue by terence410** [foliojs/linebreak#30]
in the source code "const data = base64.toByteArray(fs.readFileSync(__dirname + '/classes.trie', 'base64'));"

since browser doesn't have fs.readFileSync supports, some pre build transform is needed to load the classes.tire during build time. Anyone has some guidelines how I can do this in ReactJS? Thanks!

-- recommendations for author , instead of loading the file using fs, we might use
// const data = base64.toByteArray(fs.readFileSync(__dirname + '/classes.trie', 'base64'));

// convert the classes.tire as base64 string in JS files
const classData = "AA4IAAAAAAAAAhqg5VV7NJtZvz7fTC8zU5d.........";
const data = base64.toByteArray(classData);

**Comment by blikblum** [comment]
Try linebreak-next. When used with webpack or rollup should work

**Comment by terence410** [comment]
thx. But that package is sort of clone of the original one, but fixing the fs.readFileSync issue. I think it will be great if Arthur can do the same as you do.

meanwhile, I am able to make it work using Webpack 5. In case any one wanted to fix the issues:

npm install transform-loader buffer --save

in webpack.config.js
  module: {
    rules: [
      { test: /\.js$/, use: ["transform-loader?brfs"] }
    ],
  },

In your .js file (transform-loader will load the file and replace it with base64 string and then use Buffer to convert back to the format it needed. However, buffer is not natively supported, so we need to include that package)

const {Buffer} = require("buffer");
const LineBreaker = require("linebreak");
const lorem = 'lorem ipsum...';
const breaker = new LineBreaker(lorem);

**Comment by blikblum** [comment]
https://github.com/foliojs/linebreak/pull/18

**Comment by liborm85** [comment]
It is usually solved using brfs as mentioned above.
