### ISSUE TITLE
Update linebreak to 1.1.2

### ISSUE THREAD

**Issue by dgtllion** [foliojs/linebreak#45]
Can you please update `linebreak` module to 1.1.2? I see that only `@foliojs-fork/linebreak` is updated to 1.1.2

**Comment by liborm85** [comment]
There is nothing to update, because package `linebreak` in latest version 1.1.0 and package `@foliojs-fork/linebreak` in latest version 1.1.2 are same. (Packages have a different way of transpiling code, which is one of the reasons why the version numbers are different.)

**Comment by dgtllion** [comment]
> There is nothing to update, because package `linebreak` in latest version 1.1.0 and package `@foliojs-fork/linebreak` in latest version 1.1.2 are same. (Packages have a different way of transpiling code, which is one of the reasons why the version numbers are different.)

Is it also the same for pdfkit & fontkit?

**Comment by liborm85** [comment]
yes, currently libraries pdfkit and fontkit are not adding anything extra that is not released in original.
