### ISSUE TITLE
Can't resolve 'fs'    ERROR in ./~/linebreak/src/linebreaker.js

### ISSUE THREAD

**Issue by andylei18** [foliojs/linebreak#5]
Module not found: Error: Can't resolve 'fs' in  node_modules/linebreak/src'
 @ ./~/linebreak/src/linebreaker.js 7:7-20
 @ ./~/react-canvas/lib/measureText.js
 @ ./~/react-canvas/lib/ReactCanvas.js

**Comment by CraigMorton** [comment]
My PR #6 fixes this.

**Comment by lin-hun** [comment]
Same as

**Comment by BryanYang** [comment]
Can this use just in node env ? It can't use in brower

**Comment by CraigMorton** [comment]
Yes, this only works in node. It depends on node's built-in filesystem access module `fs` I forked the project and removed the `fs` dependency.

**Comment by liborm85** [comment]
You can use brfs as mentioned in issue https://github.com/foliojs/linebreak/issues/30.
